### ISSUE TITLE
Support terraform cloud/enterprise human friendly names for state path

### ISSUE THREAD

**Issue by p0tr3c** [snyk/driftctl#1251]
**Description**
As terraform cloud user I would like to run the driftctl with human friendly state path. 

This is a proposed extension to already supported workspace ID support for terraform cloud. Current implementation requires the user to lookup workspace id of each workspace to import. I would like to eliminate this step and allow user to use the org/workspace name structure. 

To simplify the process of importing states from the entire org we can introduce `*` wildcard which will list all workspaces in the provided org and import all states. 

I would like to propose automatically detect if provided path is workspace ID or human friendly path. 

**Example**
***Before***
```
drifctl tfstate+tfcloud://ws-L4dG719GPU9FP6Nj
```

***After***
> Specific workspace in the org
```
drifctl tfstate+tfcloud://my-org/my-workspacename
```

and 
> All workspaces in the org
```
drifctl tfstate+tfcloud://my-org/*
```

> Note: the new implementation should support both options

**Comment by eliecharra** [comment]
I totally agree with the support of the name, my question is : should we drop the ID support ? It will introduce a BC break and I'm comfortable to break this in a next 0.x version since we are still in beta.

Anyway I think this one should be splitted in two.

Adding the wildcard feature (`tfstate+tfcloud://my-org/*`) can be a dedicated issue since it will need to introduce a state enumerator.

A first step could be to change the logic to use names instead of IDs and then add the wildcard support.

**Comment by p0tr3c** [comment]
> A first step could be to change the logic to use names instead of IDs and then add the wildcard support.

We will have to resolve the name into the ID because the [API only supports](https://www.terraform.io/docs/cloud/api/state-versions.html#fetch-the-current-state-version-for-a-workspace) fetching state with ID. I am open to suggestions if keeping ID provides any value?

> Adding the wildcard feature (tfstate+tfcloud://my-org/*) can be a dedicated issue since it will need to introduce a state enumerator.

I agree this should be iterative step 👍
