### ISSUE TITLE
Add an identifier for `unmanaged` AWS security group rules 

### ISSUE THREAD

**Issue by optplx** [snyk/driftctl#1325]
**Description**
For unmanaged security group rules, the json output currently shows only a hash generated based on the security group rule properties (such as from/to ports, protocol, sg ID). As far as I can tell, this makes it impossible to identify which rule is listed using the json report, and we have to run the "raw text" report to do so.

**Example**
Here is an example of the json output for an unmanaged security group rule:
```
{
    "id": "sgrule-123456789",
    "type": "aws_security_group_rule"
}
```
Here is an example of a raw report for the same rule:
```
- sgrule-123456789
    Ports: 442, Protocol: tcp, SecurityGroup: sg-1fsdf2345dsfsdf2s, Source: 10.0.0.0/16, Type: ingress
```

Using the json one, it is not possible to identify on AWS which rule is actually behind the `sgrule-123456789`, making the json report hard to leverage here. 

**Proposition**
Would it be possible to print the real security group rule ID instead for example?

**Comment by eliecharra** [comment]
I flagged this one as a good first issue, if someone from the community want to take it, it shouldn't be too hard to handle.
Here is a few hints:

In `pkg/resource/resource.go`:
You can add new field to `SerializableResource`, something like `identityAttributes` or `humanReadableAttributes`. 
Then you need to set this field in `NewSerializableResource` based on `res.Schema().HumanReadableAttributesFunc(res)`.

An example of what is done on the console side can be found here : https://github.com/snyk/driftctl/blob/0a1ed7d01e2370fd3fed45e0120d813bdf14e7d8/pkg/cmd/scan/output/console.go#L279-L301

We may work on this on our side if nobody from the community has taken it in a couple of week since we'll need this for internal needs at some point.

Please go to discord #support channel if you need more help on this one

**Comment by wakeful** [comment]
👋 @eliecharra I created a PR for this issue

**Comment by moadibfr** [comment]
Ok I see this is the usecase for the opened PR then. Sorry I missed that.

**Comment by patch-the-dog** [comment]
This issue has been referenced in the latest release v0.21.0.
